version: '2'
catalog:
  name: tomcat80jre8-1
  version: tomcat80jre8-v1.0
  description: tomcat alpine with treafik and app download
  questions:
    - variable: "tomcat_instance"
      type: "int"
      required: true
      label: "# of tomcat instance"
      description: "how many tomcat do you get"
      default: 3

    - variable: "mem_limit"
      type: "int"
      required: true
      label: "Memory limit"
      description: "mem_limit = Xmx(JVM) + MaxPermSize(JVM) + OtherMem(cache&buffer)"
      default: 5368709120

    - variable: "java_opts"
      type: "string"
      required: false
      label: "JAVA_OPTS"
      description: "jvm opts"
      default: '-server -Xms4096m -Xmx4096m -XX:NewSize=2048m -XX:MaxNewSize=2048m -XX:PermSize=256m -XX:MaxPermSize=512m -Duser.timezone="Asia/Shanghai" -XX:+UseParallelOldGC -XX:ParallelGCThreads=4' 

    - variable: "war_file_url"
      type: "string"
      required: true
      label: "warfileURL"
      description: "you Warfile URL"
      default: "http://getsome.com/ROOT.war" 

    - variable: "lb_port"
      type: "int"
      required: true
      label: "rancher lb port"
      description: "rancher lb port expose to host"
      default: 10800 

    - variable: "traefik_enable"
      label: "Traefik proxy enable or not"
      description: "Traefik proxy enabled?"
      default: false
      required: true
      type: enum
      options:
        - false
        - true

    - variable: "treafik_frontend_rule"
      type: "string"
      required: true
      label: "treafik_frontend_rule"
      description: "traefik frontend rule,please refer to traefik doc"
      default: "Host:mydockerapp.xxx.com" 

    - variable: "treafik_default_protocal"
      label: "Traefik http/https"
      description: "http or https"
      default: http
      required: true
      type: enum
      options:
        - http
        - https

    - variable: "traefik_path"
      type: "string"
      required: true
      label: "traefik_path"
      description: "traefik_path"
      default: "/" 

services:
    tc80jre8app:
      scale: ${tomcat_instance}
      start_on_create: true 

    tc80jre8volume:
      scale: ${tomcat_instance}
      start_on_create: true

    tc80jre8:
      scale: ${tomcat_instance}
      start_on_create: true
      
    tc80jr8lb:
      scale: 2
      start_on_create: true
      lb_config:
        certs: []
        port_rules:
        - backend_name: ''
          hostname: ''
          path: ''
          priority: 1
          protocol: http
          service: tc80jre8
          source_port: ${lb_port} #18080
          target_port: 8080
          weight: 0
      health_check:
        healthy_threshold: 1
        response_timeout: 2000
        port: 42
        unhealthy_threshold: 2
        initializing_timeout: 60000
        interval: 2000
        reinitializing_timeout: 60000
