version: '2.1'

services:
  web:
    image: elkozmon/zoonavigator-web:0.4
    container_name: zoonavigator-web
    ports:
     - "${znavi_port}:8000"
    environment:
      API_HOST: "api"
      API_PORT: 9000
      API_REQUEST_TIMEOUT_MILLIS: ${api_request_timeout_millis} # 10000
    links:
     - api
    depends_on:
     - api
    restart: always
  api:
    image: elkozmon/zoonavigator-api:0.4
    container_name: zoonavigator-api
    environment:
      SERVER_HTTP_PORT: 9000
      SESSION_TTL_MILLIS: ${session_ttl_millis}
      ZK_CLIENT_TTL_MILLIS: ${zk_client_ttl_millis}
      ZK_CONNECT_TIMEOUT_MILLIS: ${zk_connect_timeout_millis}
      JVM_XMX: ${api_xmx}
      JVM_XMS: ${api_xms}
    restart: always
